frr version 8.2
frr defaults datacenter
hostname leaf2
log syslog informational
no ipv6 forwarding

interface lo
 ip address 10.255.0.12/32
!
interface eth1
 description to-spine1
 ip address 10.0.0.3/31
!
interface eth2
 description to-spine2
 ip address 10.0.0.7/31
!

router bgp 65002
 bgp router-id 10.255.0.12
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 maximum-paths 2
 !
 neighbor spines peer-group
 neighbor spines bfd
 !
 neighbor 10.0.0.2 peer-group spines
 neighbor 10.0.0.2 remote-as 65100
 neighbor 10.0.0.2 description spine1
 !
 neighbor 10.0.0.6 peer-group spines
 neighbor 10.0.0.6 remote-as 65101
 neighbor 10.0.0.6 description spine2
 !
 address-family ipv4 unicast
  network 10.255.0.12/32
  neighbor spines activate
  neighbor spines soft-reconfiguration inbound
 exit-address-family
!
