frr version 8.2
frr defaults datacenter
hostname leaf1
log syslog informational
no ipv6 forwarding

interface lo
 ip address 10.255.0.11/32
!
interface eth1
 description to-spine1
 ip address 10.0.0.1/31
!
interface eth2
 description to-spine2
 ip address 10.0.0.5/31
!

router bgp 65001
 bgp router-id 10.255.0.11
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 maximum-paths 2
 !
 neighbor spines peer-group
 neighbor spines bfd
 !
 neighbor 10.0.0.0 peer-group spines
 neighbor 10.0.0.0 remote-as 65100
 neighbor 10.0.0.0 description spine1
 !
 neighbor 10.0.0.4 peer-group spines
 neighbor 10.0.0.4 remote-as 65101
 neighbor 10.0.0.4 description spine2
 !
 address-family ipv4 unicast
  network 10.255.0.11/32
  neighbor spines activate
  neighbor spines soft-reconfiguration inbound
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor spines activate
  advertise-all-vni
 exit-address-family
!
